name: Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Make sure to use the correct repository for checkout

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}  # Use correct syntax for secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"  # Make sure 'docker-compose' is spelled correctly

      - name: Lint Code
        run: docker-compose run --rm app sh -c "flake8"  # Check if 'flake8' is installed in your Docker image


# name: CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Run a one-line script
#       run: echo "Hello, world!"
